spring:
  application:
    name: eureka-sample-client
server:
  port: 0

eureka:
  client:
    service-url: {EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
